### ISSUE TITLE
Button "cancel" has no function

### ISSUE THREAD

**Issue by hartenthaler** [dis-maja/wt-UnlinkedIndividual#1]
I would expect that clicking this button would close the "add person" window and returns to the home page of the tree.

**Comment by dis-maja** [comment]
I cant reproduce your problem, but the code is old (in my understanding of the new module system). So I replaced it with a cleaner version in v2.0.3. Please report if the problem still exists. I will let the issue stay open for a while... Thank you!

**Comment by hartenthaler** [comment]
solved!
